name: Publish ofd.ru to NPM
run-name: Publish to NPM by @${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.42

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          registry-url: 'https://registry.npmjs.org'
            
      - name: Install dependencies
        run: bun i --ignore-scripts --frozen-lockfile

      - name: Typecheck
        run: bun typecheck
      
      - name: Run Biome
        run: bun biome ci
      
      - name: Test
        run: bun run test
    
      - name: Build
        run: bun run build

      - name: Check exports
        run: bun check-exports
      
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        id: changesets
        with:
          publish: bun changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}